# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='appointment',
        ),
    ]
